### ISSUE TITLE
[RFC] Integrate cmany into CI workflow

### ISSUE THREAD

**Issue by massich** [biojppm/cmany#2]
Which would be the best way to integrate `cmany` in a CI? 
Create different environments and then call `cmany` in the building stage with all the compilers + (debug/realease) matrix?

How is your workflow?

**Comment by biojppm** [comment]
Actually, CI providers already give you the build matrix. Using cmany to build/run everything at once in your CI doesn't give you much as the the CI matrix won't be populated; you only get one monolithic build.

I do use cmany in my own development machines before pushing to the CI. I select builds of interest and batch build and/or batch run them all, while iterating improvements.

**Comment by biojppm** [comment]
I'm closing this. Feel free to reopen if you have further questions.
