### ISSUE TITLE
support Visual Studio 2019

### ISSUE THREAD

**Issue by biojppm** [biojppm/cmany#6]
... after CMake implements it!
https://gitlab.kitware.com/cmake/cmake/merge_requests/2711

**Comment by TSlivede** [comment]
It seems to me, that VS 2019 works perfectly fine - at least if I install the latest version from source.

In version 0.1.2 - which is the latest version on [github](https://github.com/biojppm/cmany/releases) and on [pypi](https://pypi.org/project/cmany/#history) - it doesn't work. This is especially bad as it means if I just do `pip install cmany` as suggested in [the manual](https://cmany.readthedocs.io/en/latest/installing/) I can't use vs2019...

Please upload a new release to pypi 😉

---

Oh, and thanks for you work! 👍

**Comment by biojppm** [comment]
Thanks for the prompt --- I've also been using the version from source, and I've been too busy to polish a new release for pypi, and that's why this bug is still open. I'll try to do it soon, hopefully within the next week.

**Comment by biojppm** [comment]
Alright, just published [version 0.1.3](https://pypi.org/project/cmany/0.1.3/) which contains the working VS2019 implementation.
